DROP TABLE IF EXISTS service_mechanic CASCADE;
DROP TABLE IF EXISTS service_part CASCADE;
DROP TABLE IF EXISTS car_service_request CASCADE;
DROP TABLE IF EXISTS invoice CASCADE;
DROP TABLE IF EXISTS mechanic CASCADE;
DROP TABLE IF EXISTS part CASCADE;
DROP TABLE IF EXISTS service CASCADE;
DROP TABLE IF EXISTS car_to_service CASCADE;
DROP TABLE IF EXISTS car_to_buy CASCADE;
DROP TABLE IF EXISTS customer CASCADE;
DROP TABLE IF EXISTS address CASCADE;
DROP TABLE IF EXISTS salesman CASCADE;
DROP TABLE IF EXISTS flyway_schema_history CASCADE;

--SELECT * FROM service_mechanic;
--SELECT * FROM service_part;
--SELECT * FROM car_service_request;
--SELECT * FROM invoice;
--SELECT * FROM mechanic;
--SELECT * FROM part;
--SELECT * FROM service;
--SELECT * FROM car_to_service;
--SELECT * FROM car_to_buy;
--SELECT * FROM customer;
--SELECT * FROM address;
--SELECT * FROM salesman;